#!/bin/sh

for i in lib/data lib/plugins etc;do
  test -d $SNAP_DATA/$i || mkdir -p $SNAP_DATA/$i
done
test -e $SNAP_DATA/etc/grafana.ini || cp $SNAP/etc/defaults.ini $SNAP_DATA/etc/grafana.ini

ulimit -n 4096
#. $SNAP_DATA/daemon_arguments
$SNAP/bin/grafana-server --config=$SNAP_DATA/etc/grafana.ini --pidfile= cfg:default.paths.logs=$SNAP_DATA/log cfg:default.paths.data=$SNAP_DATA/lib/data cfg:default.paths.plugins=$SNAP_DATA/lib/plugins
